Patch for omnitrace-sample crash with HIP API.
ROCm/omnitrace pull request #344
Opened 2024-06-05 20:46 UTC by ajanicijamd

2024-06-06 03:37 UTC, jrmadsen requested changes
LGTM except the variable initialization

2024-06-06 03:37 UTC, jrmadsen commented on source/lib/omnitrace/library/runtime.cpp
> +    uint64_t _parent_cid;
```suggestion
    uint64_t _parent_cid = 0;
```

2024-06-06 14:07 UTC, jrmadsen approved these changes

2024-06-06 20:18 UTC, dgaliffiAMD approved these changes

2024-06-07 13:52 UTC, ajanicijamd commented
Removed the unnecessary else.
I performed a squash merge and enabled signing.

2024-06-07 15:31 UTC, jrmadsen approved these changes

2024-06-07 18:59 UTC, dgaliffiAMD approved these changes
Looks good. All verified now. I'm still not sure why there is that second merge commit, though.

2024-06-07 19:22 UTC, ajanicijamd commented
I think that is because the main branch on my fork was behind the main branch on the omnitrace repo, so I had to merge this morning.

2024-06-07 19:23 UTC, merged