Changed macros verbprintf and verbprintf_bare so they write to stdout…
ROCm/omnitrace pull request #346
Opened 2024-06-12 17:26 UTC by ajanicijamd

… instead of stderr.

2024-06-12 17:39 UTC, ajanicijamd commented
This is a fix for the failing test in [SWDEV-466924](https://ontrack-internal.amd.com/browse/SWDEV-466924):
test omnitrace-avail-list-keys, which runs command
omnitrace-avail --list-keys --expand-keys
is failing because the command writes some output to stdout and some to stderr, and ctest redirects them both to the same file, where they get mixed, so the strings that the test is supposed to find ((.*)%argv%(.*)%argv_hash%) is broken in the log file.
The fix is to write everything to stdout.

2024-06-14 04:17 UTC, jrmadsen requested changes
Verbose/logging messages should be sent to `stderr`. I'd rather you just change: 

https://github.com/ROCm/omnitrace/blob/f0bd9126a5456eb9e511d13261af262d17d9b61b/source/bin/omnitrace-avail/avail.cpp#L341

to 

```cpp
          std::cout << _msg.str() << std::flush;
```

2024-06-14 04:20 UTC, jrmadsen commented
Additionally

https://github.com/ROCm/omnitrace/blob/f0bd9126a5456eb9e511d13261af262d17d9b61b/source/bin/omnitrace-avail/avail.cpp#L524

and

https://github.com/ROCm/omnitrace/blob/f0bd9126a5456eb9e511d13261af262d17d9b61b/source/bin/omnitrace-avail/avail.cpp#L529

can be bumped to level 1 or 2.

2024-06-14 18:29 UTC, ajanicijamd commented
I made those changes. Bumped the logging level to 1 for those two calls of verbprintf.

2024-06-14 20:41 UTC, jrmadsen approved these changes

2024-06-14 20:50 UTC, merged